version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_development
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3001"]
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db-data:

