apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: rohith2703/budget-app
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_USER
          value: myuser
        - name: DATABASE_PASSWORD
          value: mypassword
        - name: DATABASE_NAME
          value: myapp_development
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: rails

